name: mosviz
channels:
  - http://ssb.stsci.edu/astroconda
  - astropy-ci-extras 
  - conda-forge
dependencies:
  - glueviz>=0.9.0 
  - astropy>=1.2 
  - matplotlib>=1.5.3 
  - numpy 
  - cython 
  - pyqt
